version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: techstore-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=techstore

  # Database seeder service
  db-seeder:
    build:
      context: .
      dockerfile: Dockerfile.seed
    container_name: techstore-seeder
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - MONGODB_URI=mongodb://mongo:27017/techstore
      - EXPORT_PATH=/app/mongodb_export
    volumes:
      - ./mongodb_export:/app/mongodb_export
      - ./models:/app/models
      - ./db:/app/db

  # Web application service
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: techstore-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - MONGODB_URI=mongodb://mongo:27017/techstore
      - HOST=0.0.0.0
      # Keep the existing environment variables from .env, but override MONGODB_URI
      # Add any environment variables that need to be different in Docker here
    volumes:
      # Mount your local directory, but don't overwrite node_modules in the container
      - ./:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: